# After changing this file, check it on:
#   http://lint.travis-ci.org/
language: python
python:
  - 2.7
install:
  - pip install -r requirements.txt
script:
  - python runtests.py
notifications:
  email: false
